-- =====================================================================
-- SmartTds  PER-YEAR database template  (PostgreSQL)
-- Converted from SmartTds26Script.sql (SQL Server). 14 tables.
-- Apply once per assessment year:  CREATE DATABASE smarttds26; \c smarttds26; \i this_file
--
-- CONVERSION CONVENTIONS (see PHASE1_SCHEMA_NOTES.md):
--   * all identifiers lowercased (PG folds unquoted -> lowercase; Npgsql
--     reader["MixedCase"] lookup is case-insensitive, so C# mapping + the
--     existing bracket-stripped BAL queries keep working).
--   * int IDENTITY(1,1)      -> integer GENERATED BY DEFAULT AS IDENTITY
--   * nvarchar(n)            -> varchar(n)
--   * bit                    -> boolean   (default 0->false, 1->true)
--   * datetime               -> timestamp
--   * getdate()              -> now()
--   * numeric/decimal(p,s)   -> numeric(p,s)   (preserved exactly)
--   * RESERVED WORD: column "desc" (F15hn) MUST be quoted everywhere.
-- =====================================================================

-- ---------- AddChallan ----------
CREATE TABLE addchallan (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chid            integer,
    ayid            integer NOT NULL,
    subcode         integer NOT NULL,
    challandt       varchar(10),
    challanno       varchar(20),
    totaltds        numeric(14,2),
    tax             numeric(14,2),
    surchrg         numeric(14,2),
    cess            numeric(14,2),
    total           numeric(14,2),
    interest        numeric(14,2),
    others          varchar(50),
    fee234e         numeric(14,2),
    grndtotal       numeric(14,2),
    namebnk         varchar(50),
    address         varchar(200),
    branchcd        varchar(50),
    mode            varchar(50),
    cheqno          varchar(50),
    drawnon         varchar(50),
    minorcd         varchar(50),
    actualtds       varchar(50),
    deductedtds     varchar(50),
    depositedtds    varchar(50),
    intq1           numeric(18,2) NOT NULL DEFAULT 0,
    intq2           numeric(18,2) NOT NULL DEFAULT 0,
    intq3           numeric(18,2) NOT NULL DEFAULT 0,
    intq4           numeric(18,2) NOT NULL DEFAULT 0,
    formtype        varchar(10),
    isfromitdportal boolean NOT NULL DEFAULT false
);

-- ---------- ApplicationParams ----------
CREATE TABLE applicationparams (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(100),
    value   varchar(100)
);

-- ---------- Ddodet ----------
CREATE TABLE ddodet (
    tid         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer DEFAULT 0,
    ayid        integer DEFAULT 0,
    period      integer DEFAULT 0,
    aocode      integer DEFAULT 0,
    dcode       integer DEFAULT 0,
    tax         numeric(18,2) DEFAULT 0,
    tds         numeric(18,2) DEFAULT 0,
    nature      varchar(50),
    mapcode     varchar(50),
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- F15hn ----------  (note quoted reserved word "desc")
CREATE TABLE f15hn (
    tid         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer DEFAULT 0,
    ayid        integer DEFAULT 0,
    pcode       integer DEFAULT 0,
    amount      numeric(18,2) DEFAULT 0,
    "desc"      varchar(500),
    date        varchar(50),
    nature      varchar(100),
    section     varchar(50),
    income      numeric(18,2) DEFAULT 0,
    quarter     varchar(10),
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- F15hnPayee ----------
CREATE TABLE f15hnpayee (
    tid         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer DEFAULT 0,
    ayid        integer DEFAULT 0,
    pcode       integer DEFAULT 0,
    formid      integer DEFAULT 0,
    date15g     varchar(50),
    date15g2    varchar(50),
    date15g3    varchar(50),
    unqno15g    varchar(100),
    nof15g      integer DEFAULT 0,
    value15g    numeric(18,2) DEFAULT 0,
    eincome     numeric(18,2) DEFAULT 0,
    cincome     numeric(18,2) DEFAULT 0,
    amtpaid     numeric(18,2) DEFAULT 0,
    layr        varchar(50),
    type        varchar(10),
    quarter     varchar(10),
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- FilingStatus ----------
CREATE TABLE filingstatus (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode integer NOT NULL,
    ayid    integer NOT NULL,
    f241r varchar(100) DEFAULT '', f241d varchar(50) DEFAULT '',
    f242r varchar(100) DEFAULT '', f242d varchar(50) DEFAULT '',
    f243r varchar(100) DEFAULT '', f243d varchar(50) DEFAULT '',
    f244r varchar(100) DEFAULT '', f244d varchar(50) DEFAULT '',
    f261r varchar(100) DEFAULT '', f261d varchar(50) DEFAULT '',
    f262r varchar(100) DEFAULT '', f262d varchar(50) DEFAULT '',
    f263r varchar(100) DEFAULT '', f263d varchar(50) DEFAULT '',
    f264r varchar(100) DEFAULT '', f264d varchar(50) DEFAULT '',
    f271r varchar(100) DEFAULT '', f271d varchar(50) DEFAULT '',
    f272r varchar(100) DEFAULT '', f272d varchar(50) DEFAULT '',
    f273r varchar(100) DEFAULT '', f273d varchar(50) DEFAULT '',
    f274r varchar(100) DEFAULT '', f274d varchar(50) DEFAULT '',
    tcs1r varchar(100) DEFAULT '', tcs1d varchar(50) DEFAULT '',
    tcs2r varchar(100) DEFAULT '', tcs2d varchar(50) DEFAULT '',
    tcs3r varchar(100) DEFAULT '', tcs3d varchar(50) DEFAULT '',
    tcs4r varchar(100) DEFAULT '', tcs4d varchar(50) DEFAULT ''
);

-- ---------- Payee ----------
CREATE TABLE payee (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer NOT NULL,
    ayid        integer NOT NULL,
    tsid        integer,
    empflag     varchar(1),
    pan         varchar(20),
    panstatus   varchar(10),
    name        varchar(100) NOT NULL,
    add1        varchar(200),
    add2        varchar(200),
    add3        varchar(200),
    add4        varchar(200),
    city        varchar(50),
    dob         varchar(10),
    doj         varchar(10),
    fname       varchar(100),
    phone       varchar(12),
    phone2      varchar(12),
    pincode     integer,
    zipcode     integer,
    statename   varchar(50),
    tin         varchar(20),
    usercode    varchar(20),
    empdesig    varchar(50),
    stcode      varchar(20),
    dol         varchar(10),
    dor         varchar(10),
    leaves      varchar(12),
    email       varchar(50),
    email2      varchar(50),
    panstat     varchar(10),
    flag206abcca varchar(1),
    flag115bac  varchar(1),
    freezepan   boolean,
    sex         varchar(1),
    status      varchar(20),
    rstatus     varchar(20),
    country     integer,
    state       integer,
    dirflag     boolean,
    taxregime   varchar(20) DEFAULT 'AUTOMATIC'
);

-- ---------- Salary ----------
CREATE TABLE salary (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode                     integer NOT NULL,
    ayid                        integer NOT NULL,
    saltype                     varchar(10) NOT NULL,
    nameofemployer              varchar(125) NOT NULL,
    natureofemployment          varchar(10) NOT NULL,
    panofemployer               varchar(10),
    tanofemployer               varchar(10),
    countrycode                 integer,
    addrdetail                  varchar(200) NOT NULL,
    cityortownordistrict        varchar(50) NOT NULL,
    statecode                   varchar(2) NOT NULL,
    pincode                     integer,
    zipcode                     varchar(10),
    grosssalary                 numeric(15,0) NOT NULL,
    valueofperquisites          numeric(15,0) NOT NULL,
    profitsinlieuofsalary       numeric(15,0) NOT NULL DEFAULT 0,
    incomenotified89a           numeric(15,0) NOT NULL DEFAULT 0,
    incomenotifiedother89a      numeric(15,0) NOT NULL DEFAULT 0,
    incomenotifiedpryr89a       numeric(15,0) NOT NULL DEFAULT 0,
    allwncexemptus10            numeric(15,0),
    increliefus89a              numeric(15,0),
    deductionundersection16ia   numeric(5,0),
    entertainmntalwncus16ii     numeric(4,0),
    professionaltaxus16iii      numeric(4,0),
    hra                         numeric(15,0),
    actualrent                  numeric(15,0),
    whethermetro                boolean NOT NULL,
    exempthra                   numeric(15,0),
    hrasalary                   numeric(15,0),
    arrears                     numeric(15,0),
    taxablesalary               numeric(15,0),
    taxablesalarynew            numeric(15,0),
    deductionundersection16iaflag boolean NOT NULL DEFAULT true,
    deductionundersection16ianew  numeric(8,0),
    dearnessallwnc              numeric(12,0),
    pcode                       integer
);
CREATE INDEX ix_salary_lookup ON salary (subcode, ayid, pcode);

-- ---------- SalaryExemptAllowances ----------
CREATE TABLE salaryexemptallowances (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salid           integer NOT NULL REFERENCES salary(id) ON DELETE CASCADE,
    salnaturedesc   varchar(50) NOT NULL,
    salothnatofinc  varchar(500) NOT NULL,
    salothamount    numeric(15,0) NOT NULL
);

-- ---------- SalaryNatureDetails ----------
CREATE TABLE salarynaturedetails (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salid       integer NOT NULL REFERENCES salary(id) ON DELETE CASCADE,
    naturedesc  varchar(10) NOT NULL,
    othnatofinc varchar(500) NOT NULL,
    othamount   numeric(15,0) NOT NULL
);

-- ---------- SalaryPerquisiteDetails ----------
CREATE TABLE salaryperquisitedetails (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salid       integer NOT NULL REFERENCES salary(id) ON DELETE CASCADE,
    naturedesc  varchar(10) NOT NULL,
    othnatofinc varchar(500) NOT NULL,
    othamount   numeric(15,0) NOT NULL
);

-- ---------- TdsCompIncome ----------
CREATE TABLE tdscompincome (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode         integer,
    ayid            integer,
    pcode           integer,
    salary_id       integer DEFAULT 0,
    salaryold       numeric(14,2) DEFAULT 0,  salarynew       numeric(14,2) DEFAULT 0,
    businessold     numeric(14,2) DEFAULT 0,  businessnew     numeric(14,2) DEFAULT 0,
    propertyold     numeric(14,2) DEFAULT 0,  propertynew     numeric(14,2) DEFAULT 0,
    stcgold         numeric(14,2) DEFAULT 0,  stcgnew         numeric(14,2) DEFAULT 0,
    cg20old         numeric(14,2) DEFAULT 0,  cg20new         numeric(14,2) DEFAULT 0,
    cg125old        numeric(14,2) DEFAULT 0,  cg125new        numeric(14,2) DEFAULT 0,
    othersrcold     numeric(14,2) DEFAULT 0,  othersrcnew     numeric(14,2) DEFAULT 0,
    nscintold       numeric(14,2) DEFAULT 0,  nscintnew       numeric(14,2) DEFAULT 0,
    proplossold     numeric(14,2) DEFAULT 0,  proplossnew     numeric(14,2) DEFAULT 0,
    lotteryold      numeric(14,2) DEFAULT 0,  lotterynew      numeric(14,2) DEFAULT 0,
    agriold         numeric(14,2) DEFAULT 0,  agrinew         numeric(14,2) DEFAULT 0,
    gtiold          numeric(14,2) DEFAULT 0,  gtinew          numeric(14,2) DEFAULT 0,
    ded80cold       numeric(14,2) DEFAULT 0,  ded80cnew       numeric(14,2) DEFAULT 0,
    dedviaold       numeric(14,2) DEFAULT 0,  dedvianew       numeric(14,2) DEFAULT 0,
    totalincomeold  numeric(14,2) DEFAULT 0,  totalincomenew  numeric(14,2) DEFAULT 0,
    taxcg20old      numeric(14,2) DEFAULT 0,  taxcg20new      numeric(14,2) DEFAULT 0,
    taxcg125old     numeric(14,2) DEFAULT 0,  taxcg125new     numeric(14,2) DEFAULT 0,
    taxotherincold  numeric(14,2) DEFAULT 0,  taxotherincnew  numeric(14,2) DEFAULT 0,
    taxlotteryold   numeric(14,2) DEFAULT 0,  taxlotterynew   numeric(14,2) DEFAULT 0,
    totaltaxold     numeric(14,2) DEFAULT 0,  totaltaxnew     numeric(14,2) DEFAULT 0,
    rebate87aold    numeric(14,2) DEFAULT 0,  rebate87anew    numeric(14,2) DEFAULT 0,
    surchargeold    numeric(14,2) DEFAULT 0,  surchargenew    numeric(14,2) DEFAULT 0,
    cessold         numeric(14,2) DEFAULT 0,  cessnew         numeric(14,2) DEFAULT 0,
    taxpayableold   numeric(14,2) DEFAULT 0,  taxpayablenew   numeric(14,2) DEFAULT 0,
    reliefold       numeric(14,2) DEFAULT 0,  reliefnew       numeric(14,2) DEFAULT 0,
    nettaxold       numeric(14,2) DEFAULT 0,  nettaxnew       numeric(14,2) DEFAULT 0,
    adoptedmethod   varchar(20) DEFAULT 'AUTOMATIC',
    cert197         varchar(26),
    adoptedtax      numeric(14,2) DEFAULT 0,
    prevempsalary   numeric(14,2) DEFAULT 0,
    prevemptds      numeric(14,2) DEFAULT 0,
    prevempbasic    numeric(14,2) DEFAULT 0,
    tds192_2b       numeric(14,2) DEFAULT 0,
    tax192_1a       numeric(14,2) DEFAULT 0,
    modifiedon      timestamp DEFAULT now(),
    isdeleted       boolean DEFAULT false
);

-- ---------- TdsDeduction ----------
CREATE TABLE tdsdeduction (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer,
    ayid        integer,
    pcode       integer,
    ded80id     integer,
    amount      numeric(14,2) DEFAULT 0,
    amount1     numeric(14,2) DEFAULT 0,
    amount2     numeric(14,2) DEFAULT 0,
    amount3     numeric(14,2) DEFAULT 0,
    amount4     numeric(14,2) DEFAULT 0,
    amount5     numeric(14,2) DEFAULT 0,
    amount6     numeric(14,2) DEFAULT 0,
    amount7     numeric(14,2) DEFAULT 0,
    dedamt      numeric(14,2) DEFAULT 0,
    dedamt2     numeric(14,2) DEFAULT 0,
    grossamt    numeric(14,2) DEFAULT 0,
    senior      boolean DEFAULT false,
    ssenior     boolean DEFAULT false,
    severe      boolean DEFAULT false,
    date        varchar(20),
    salary_id   integer,
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- TdsEntry ----------
CREATE TABLE tdsentry (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payeeid     integer,
    chid        integer,
    subcode     integer NOT NULL,
    ayid        integer NOT NULL,
    payeename   varchar(100),
    payername   varchar(100),
    section     integer,
    nature      integer,
    descrp      varchar(100),
    datepayment varchar(10),
    datededuct  varchar(10),
    typededuct  varchar(50),
    amtpay      numeric(14,2),
    tdsrate     numeric(5,2),
    surcharge   numeric(14,2),
    tdsdeduct   numeric(14,2),
    surdeduct   numeric(14,2),
    cess        numeric(14,2),
    datedeposit varchar(10),
    totaltds2   numeric(14,2),
    tdsdedlater numeric(14,2),
    formtype    varchar(5),
    tdsapp      varchar(10),
    ack15ca     varchar(26),
    certno      varchar(26),
    dtvalf      varchar(10),
    dtvalt      varchar(10),
    dtpaying    varchar(10),
    dtcomm      varchar(10),
    evalid      boolean,
    actualtds   numeric(14,2),
    actualrate  numeric(5,2),
    chinterest  numeric(14,2),
    chtdsdep    numeric(14,2),
    deductioncode varchar(100),
    pcode       integer DEFAULT 0,
    liable394   varchar(1),
    challan394  varchar(10),
    datepay394  varchar(10)
);
