-- =====================================================================
-- SmartTds  MASTER database schema  (PostgreSQL)
-- Converted from MasterDbTdsScript.utf8.sql (SQL Server). 28 tables.
-- Apply once:  CREATE DATABASE smarttds_master; \c smarttds_master; \i this_file
--
-- CONVERSION CONVENTIONS (see PHASE1_SCHEMA_NOTES.md):
--   * all identifiers lowercased (PG folds unquoted -> lowercase; Npgsql
--     reader lookups are case-insensitive, so C# mapping keeps working).
--   * int IDENTITY(1,1)      -> integer GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT so seed rows can carry explicit ids)
--   * nvarchar(n)            -> varchar(n)
--   * nvarchar(max)          -> text
--   * bit                    -> boolean   (default 0->false, 1->true)
--   * datetime / smalldatetime -> timestamp
--   * decimal(p,s)/numeric(p,s) -> numeric(p,s)   (preserved exactly)
--   * float / real           -> double precision
--   * image / varbinary      -> bytea
--   * date                   -> date   (kept as-is; SQL Server date = PG date)
--   * getdate()              -> now()
--   * RESERVED WORD columns that require quoting (verified against PG16):
--       "limit"  -> column in tdsentriessection and tdsrate (LIMIT is reserved).
--       These MUST be quoted in the BAL queries too. All other identifiers
--       here (name, value, mode, date, number, period, state, status, section)
--       are NON-reserved in PG and need no quoting.
--   * FOREIGN KEYS are added at the END of this file (after all tables) so
--     creation order is independent of declaration order.
-- =====================================================================

-- ---------- ApplicationParams ----------
CREATE TABLE applicationparams (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(100),
    value   text
);

-- ---------- Assessee ----------
CREATE TABLE assessee (
    subcode                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodkey                     varchar(10) NOT NULL,
    filecode                    varchar(10),
    groupcode                   integer,
    tradename                   varchar(125) NOT NULL,
    firstname                   varchar(25) NOT NULL,
    middlename                  varchar(25),
    lastname                    varchar(75),
    fathername                  varchar(125),
    husbandname                 varchar(125),
    assesseestatus              varchar(10) NOT NULL DEFAULT '01',
    assesseesubstatus           varchar(10),
    dob                         varchar(10),
    sex                         varchar(1),
    pan                         varchar(10) NOT NULL,
    panstatus                   varchar(50),
    tan                         varchar(10),
    cin                         varchar(50),
    gstno                       varchar(15),
    aadhaarno                   varchar(12),
    aadhaarnrolment             varchar(28),
    aadharstatus                varchar(50),
    sebiregno                   varchar(15),
    principalpan                varchar(10),
    citizenshipcode             varchar(50),
    citizenshipoth              varchar(50),
    residentstatus              varchar(50),
    passportno                  varchar(50),
    mobileprimarystdcode        varchar(10),
    mobileprimary               varchar(11),
    mobileprimarybelongsto      varchar(50),
    mobilesecondarystdcode      varchar(10),
    mobilesecondary             varchar(11),
    mobilesecondarybelongsto    varchar(50),
    mobileresistdcode           varchar(50),
    mobileresi                  varchar(11),
    phoneresistdcode            varchar(5),
    phoneresi                   varchar(11),
    emailprimary                varchar(125),
    emailprimarybelongsto       varchar(50),
    emailsecondary              varchar(125),
    emailsecondarybelongsto     varchar(50),
    addr1                       varchar(50),
    addr2                       varchar(50),
    addr3                       varchar(50),
    addr4                       varchar(50),
    postofccode                 integer,
    othpostofcname              varchar(50),
    pincode                     integer,
    zipcode                     varchar(50),
    citycode                    integer,
    othcityname                 varchar(50),
    statecode                   integer,
    othstatename                varchar(50),
    countrycode                 integer,
    communicationaddrto         varchar(50),
    areacode                    varchar(3),
    aotype                      varchar(2),
    aono                        varchar(10),
    rangecode                   varchar(10),
    jurisdiction                varchar(50),
    jurisdictionemail           varchar(125),
    jurisdictionbuildingname    varchar(100),
    ward                        varchar(15),
    auditcase                   boolean NOT NULL DEFAULT false,
    verifiedby                  varchar(125),
    referredby                  varchar(125),
    consultantid                integer,
    startay                     integer,
    enday                       integer,
    userid                      varchar(20),
    password                    text,
    dsccommonname               varchar(100),
    dscexpirydt                 varchar(50),
    dsclinkedflag               varchar(50),
    recgnnumallottedbydpiit     varchar(50),
    certificationnumber         varchar(50),
    dateoffilingform2           varchar(10),
    lastlogin                   varchar(50),
    lastlogout                  varchar(50),
    lastupdated                 varchar(50),
    profilepic                  bytea,
    createdby                   integer NOT NULL,
    createdon                   timestamp NOT NULL,
    modifiedby                  integer NOT NULL,
    modifiedon                  timestamp NOT NULL,
    isdeleted                   boolean NOT NULL,
    leino                       varchar(20),
    leivaldupto                 varchar(10),
    prannum                     varchar(20),
    authname                    varchar(100),
    authdob                     varchar(10),
    authpan                     varchar(10),
    authdesignation             varchar(50),
    authaddr1                   varchar(75),
    authaddr2                   varchar(75),
    authaddr3                   varchar(75),
    authcity                    varchar(75),
    authpin                     integer,
    authstate                   varchar(50),
    authsex                     varchar(1),
    authfname                   varchar(100),
    authstdcode1                varchar(5),
    authmobile1                 varchar(15),
    authstdcode2                varchar(5),
    authmobile2                 varchar(15),
    authstdph1                  varchar(5),
    authphone1                  varchar(10),
    authstdph2                  varchar(5),
    authphone2                  varchar(10),
    authemail1                  varchar(50),
    authemail2                  varchar(50),
    govstate                    varchar(50),
    govpao                      varchar(25),
    govpaoname                  varchar(50),
    govddo                      varchar(25),
    govddono                    varchar(25),
    govministryname             varchar(50),
    govministrynameoth          varchar(50),
    govain                      varchar(25),
    branchname                  varchar(50),
    whetherint                  boolean,
    pendingbill                 boolean,
    applicableforms             varchar(50) DEFAULT '24Q,26Q,27Q,27EQ',
    tdscpcpwd                   varchar(100)
);

-- ---------- AssesseeRep ----------
CREATE TABLE assesseerep (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode         integer NOT NULL,
    repname         varchar(125) NOT NULL,
    repfathername   varchar(125),
    reppan          varchar(10),
    repcapacity     varchar(5),
    repaddress      varchar(250),
    repaadhaar      varchar(12),
    place           varchar(50),
    isdeleted       boolean NOT NULL
);

-- ---------- AssesseeResStatus ----------
CREATE TABLE assesseeresstatus (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode         integer NOT NULL,
    ayid            integer NOT NULL,
    resstatus       varchar(10) NOT NULL,
    modifiedon      timestamp NOT NULL,
    resstatusval    text
);

-- ---------- AyMaster ----------
CREATE TABLE aymaster (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayid        integer NOT NULL,
    name        varchar(15) NOT NULL,
    startdt     varchar(10) NOT NULL,
    enddt       varchar(10) NOT NULL,
    nonbusinc   varchar(10),
    businc      varchar(10),
    auditcase   varchar(10),
    compcase    varchar(10),
    case94e     varchar(10),
    advinst1    varchar(10),
    advinst2    varchar(10),
    advinst3    varchar(10),
    advinst4    varchar(10),
    updnonbusinc varchar(10),
    updbusinc   varchar(10),
    updauditcase varchar(10),
    updcompcase varchar(10),
    updcase94e  varchar(10)
);

-- ---------- BankDetails ----------
CREATE TABLE bankdetails (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode         integer NOT NULL,
    bankname        varchar(125) NOT NULL,
    branchname      varchar(50) NOT NULL,
    bankadd         varchar(50),
    bankacno        varchar(20) NOT NULL,
    ifsccode        varchar(11) NOT NULL,
    bsrno           varchar(79),
    micrno          varchar(9),
    typecode        varchar(50),
    ecs             varchar(10) NOT NULL,
    createdby       integer NOT NULL,
    createdon       timestamp NOT NULL,
    modifiedby      integer NOT NULL,
    modifiedon      timestamp NOT NULL,
    isdeleted       boolean NOT NULL,
    appliestoyear   varchar(100) NOT NULL DEFAULT '0'
);

-- ---------- BillDetails ----------
CREATE TABLE billdetails (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billid          integer NOT NULL,
    description     varchar(50) NOT NULL,
    prodcode        numeric(8,0),
    unit            varchar(10),
    qty             numeric(12,2),
    value           numeric(15,2) NOT NULL,
    discount        numeric(18,2),
    taxablevalue    numeric(15,2) NOT NULL,
    ratemain        numeric(5,2) NOT NULL,
    amtigst         numeric(15,2),
    amtcgst         numeric(15,2),
    amtsgst         numeric(15,2),
    amtcess         numeric(15,2),
    totamount       numeric(15,2) NOT NULL
);

-- ---------- BillHead ----------
CREATE TABLE billhead (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode         integer NOT NULL,
    ayid            integer NOT NULL,
    periodid        integer,
    conscode        integer NOT NULL,
    billno          integer NOT NULL,
    billdt          date NOT NULL,
    pos             integer NOT NULL,
    totamt          numeric(15,3) NOT NULL,
    amtreceived     numeric(15,3) NOT NULL,
    amtdisc         numeric(15,3) NOT NULL,
    createdby       integer,
    createdon       timestamp,
    modifiedby      integer,
    modifiedon      timestamp,
    isdeleted       boolean NOT NULL DEFAULT false
);

-- ---------- Billmast ----------
CREATE TABLE billmast (
    billid      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        varchar(50),
    subcode     integer DEFAULT 0,
    billno      integer DEFAULT 0,
    p1          varchar(500),
    p1amt       numeric(18,2) DEFAULT 0,
    p2          varchar(500),
    p2amt       numeric(18,2) DEFAULT 0,
    p3          varchar(500),
    p3amt       numeric(18,2) DEFAULT 0,
    p4          varchar(500),
    p4amt       numeric(18,2) DEFAULT 0,
    p5          varchar(500),
    p5amt       numeric(18,2) DEFAULT 0,
    p6          varchar(500),
    p6amt       numeric(18,2) DEFAULT 0,
    p7          varchar(500),
    p7amt       numeric(18,2) DEFAULT 0,
    p8          varchar(500),
    p8amt       numeric(18,2) DEFAULT 0,
    p9          varchar(500),
    p9amt       numeric(18,2) DEFAULT 0,
    p10         varchar(500),
    p10amt      numeric(18,2) DEFAULT 0,
    stax        numeric(18,2) DEFAULT 0,
    tamt        numeric(18,2) DEFAULT 0,
    sperc       numeric(18,2) DEFAULT 0,
    ramt        numeric(18,2) DEFAULT 0,
    ayid        integer DEFAULT 0,
    conscode    integer DEFAULT 0,
    damt        numeric(18,2) DEFAULT 0,
    receipt     boolean DEFAULT false,
    grpcode     integer DEFAULT 0,
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- BillReceipt ----------
CREATE TABLE billreceipt (
    receiptno   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        varchar(50),
    subcode     integer DEFAULT 0,
    billno      integer DEFAULT 0,
    amount      numeric(18,2) DEFAULT 0,
    mode        varchar(50),
    number      varchar(100),
    billdate    varchar(50),
    ayid        integer DEFAULT 0,
    conscode    integer DEFAULT 0,
    discount    numeric(18,2) DEFAULT 0,
    billid      integer DEFAULT 0,
    userid      integer DEFAULT 0,
    lastupdate  varchar(50),
    modifiedon  timestamp DEFAULT now(),
    isdeleted   boolean DEFAULT false
);

-- ---------- BillReceipts ----------
CREATE TABLE billreceipts (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ayid            integer NOT NULL,
    billid          integer NOT NULL,
    receiptno       integer NOT NULL,
    receiptdt       date NOT NULL,
    amtreceived     numeric(15,3) NOT NULL,
    amtdisc         numeric(15,3) NOT NULL,
    mode            varchar(50) NOT NULL,
    instrumentno    varchar(50),
    instrumentdt    date,
    createdby       integer,
    createdon       timestamp,
    modifiedby      integer,
    modifiedon      timestamp,
    isdeleted       boolean NOT NULL DEFAULT false
);

-- ---------- Check_period ----------
CREATE TABLE check_period (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quarter     integer DEFAULT 0,
    month       integer DEFAULT 0,
    ayid        integer DEFAULT 0
);

-- ---------- Consultant ----------
CREATE TABLE consultant (
    conscode                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodkey                         varchar(10) NOT NULL,
    name                            varchar(50) NOT NULL,
    residenceno                     varchar(50) NOT NULL,
    residencename                   varchar(50) NOT NULL,
    roadorstreet                    varchar(50) NOT NULL,
    localityorarea                  varchar(50),
    city                            varchar(50) NOT NULL,
    statecode                       varchar(50),
    state                           varchar(50) NOT NULL,
    phoneoffice                     varchar(11) NOT NULL,
    phoneresi                       varchar(50) NOT NULL,
    mobile                          varchar(11) NOT NULL,
    mobile2                         varchar(50) NOT NULL,
    email                           varchar(125) NOT NULL,
    partnername                     varchar(50) NOT NULL,
    membership                      varchar(20),
    partnerdesignation              varchar(50) NOT NULL,
    slogan                          varchar(32) NOT NULL,
    bankname                        varchar(100),
    accno                           varchar(25),
    ifsccode                        varchar(11),
    panfirm                         varchar(10),
    frnno                           varchar(7),
    panpartner                      varchar(10),
    pin                             numeric(7,0) NOT NULL,
    gstno                           varchar(15),
    userid                          varchar(10),
    pwd                             varchar(25),
    emailprovider                   varchar(20),
    emailid                         varchar(50),
    emailpwd                        varchar(50),
    flagdefault                     boolean NOT NULL,
    logo                            text,
    emailsignature                  text,
    flagpendingbillsnotifications   boolean NOT NULL DEFAULT true,
    createdby                       integer NOT NULL,
    createdon                       timestamp NOT NULL,
    modifiedby                      integer NOT NULL,
    modifiedon                      timestamp NOT NULL,
    isdeleted                       boolean NOT NULL
);

-- ---------- Country ----------
CREATE TABLE country (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    integer NOT NULL,
    name    varchar(50) NOT NULL
);

-- ---------- District ----------
CREATE TABLE district (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        integer NOT NULL,
    statecode   integer NOT NULL,
    name        varchar(255) NOT NULL
);

-- ---------- FeePaidMarking ----------
CREATE TABLE feepaidmarking (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode     integer NOT NULL,
    fyid        integer NOT NULL,
    periodid    integer,
    feepaid     boolean NOT NULL DEFAULT false,
    notes       text,
    createdon   timestamp NOT NULL,
    modifiedon  timestamp
);

-- ---------- Groups ----------
CREATE TABLE groups (
    grpcode     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodkey     varchar(10) NOT NULL,
    groupname   varchar(100),
    createdby   integer NOT NULL,
    createdon   timestamp NOT NULL,
    modifiedby  integer NOT NULL,
    modifiedon  timestamp NOT NULL,
    isdeleted   boolean NOT NULL DEFAULT false,
    email       varchar(75),
    mobile      varchar(10)
);

-- ---------- Pincode ----------
-- (no IDENTITY in source; no PK defined; use serial for consistency)
CREATE TABLE pincode (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pincode         double precision,
    districtcode    double precision,
    statecode       double precision,
    subdistrictcode double precision,
    localitycode    double precision,
    postofficecode  double precision
);

-- ---------- PostOffice ----------
CREATE TABLE postoffice (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    integer NOT NULL,
    name    varchar(255) NOT NULL
);

-- ---------- ReturnDates ----------
-- No explicit IDENTITY PK in source; add serial surrogate for PG
CREATE TABLE returndates (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcode             integer NOT NULL,
    ayid                integer NOT NULL,
    quarter             varchar(5) NOT NULL,
    signingdate         varchar(10) NOT NULL,
    place               varchar(75),
    formname            varchar(10) NOT NULL,
    tokennumber         varchar(15),
    addresschangeorg    boolean NOT NULL DEFAULT false,
    addresschangeauth   boolean NOT NULL DEFAULT false,
    aoapprovalnu        varchar(20),
    isregularstatement  boolean NOT NULL DEFAULT true,
    isnilreturn         boolean NOT NULL DEFAULT false,
    nilsectionscount    integer NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_returndates_perquarterform
    ON returndates (subcode, ayid, quarter, formname);

-- ---------- State ----------
CREATE TABLE state (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    integer NOT NULL,
    name    varchar(50) NOT NULL
);

-- ---------- SubDistrict ----------
CREATE TABLE subdistrict (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    integer NOT NULL,
    name    varchar(50) NOT NULL
);

-- ---------- Tdsaomaster ----------
CREATE TABLE tdsaomaster (
    aocode      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aoin        varchar(50),
    laoin       varchar(50),
    name        varchar(200),
    add1        varchar(200),
    add2        varchar(200),
    add3        varchar(200),
    add4        varchar(200),
    city        varchar(100),
    statecode   integer DEFAULT 0,
    pin         integer DEFAULT 0,
    std         varchar(20),
    phone       varchar(50),
    email       varchar(200),
    aperson     varchar(200),
    adesig      varchar(200),
    cat         varchar(50),
    lataocat    varchar(50),
    radd1       varchar(200),
    radd2       varchar(200),
    radd3       varchar(200),
    radd4       varchar(200),
    rcity       varchar(100),
    rstatecode  integer DEFAULT 0,
    rpin        varchar(20),
    rstd        varchar(20),
    rphone      varchar(50),
    remail      varchar(200),
    rmobile     varchar(50),
    minname     varchar(200),
    sminname    varchar(200),
    sminname2   varchar(200),
    paoregno    integer DEFAULT 0,
    statename   varchar(100),
    mobile      varchar(50)
);

-- ---------- Tdsded80 ----------
CREATE TABLE tdsded80 (
    ded80id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedsec      varchar(20),
    ded80name   varchar(200),
    ded80table  varchar(50),
    label1      varchar(200),
    label2      varchar(200),
    label3      varchar(200),
    label4      varchar(200),
    label5      varchar(200),
    label6      varchar(200),
    label7      varchar(200),
    label8      varchar(200),
    label9      varchar(200),
    label10     varchar(200),
    dedtype     varchar(50),
    pdedid      integer DEFAULT 0,
    section     varchar(20),
    short       varchar(50),
    ind         boolean DEFAULT false,
    indnr       boolean DEFAULT false,
    huf         boolean DEFAULT false,
    hufnr       boolean DEFAULT false,
    firm        boolean DEFAULT false,
    company     boolean DEFAULT false,
    companynr   boolean DEFAULT false,
    coop        boolean DEFAULT false,
    sortid      integer DEFAULT 0,
    ayid        integer DEFAULT 0,
    ayid2       integer DEFAULT 0
);

-- ---------- TdsEntriesSection ----------
-- No PK in source
CREATE TABLE tdsentriessection (
    section     varchar(10),
    paycode     integer,
    name        varchar(200),
    "limit"     integer,
    formname    varchar(6),
    newsection  varchar(50)
);

-- ---------- TdsNature ----------
CREATE TABLE tdsnature (
    particular  varchar(255),
    code        integer NOT NULL,
    CONSTRAINT pk_nature3 PRIMARY KEY (code)
);

-- ---------- TdsRate ----------
-- No PK in source
CREATE TABLE tdsrate (
    ayid    integer,
    tsid    integer,
    paycode integer,
    rate    numeric(5,2),
    surch   numeric(5,2),
    "limit" integer
);

-- ---------- Users ----------
CREATE TABLE users (
    userid                  integer GENERATED BY DEFAULT AS IDENTITY,
    prodkey                 varchar(10) NOT NULL,
    username                varchar(50) NOT NULL,
    name                    varchar(50) NOT NULL,
    pwd                     varchar(500) NOT NULL,
    emailid                 varchar(150) NOT NULL,
    mobile                  varchar(10) NOT NULL,
    usertype                varchar(40) NOT NULL,
    assesseeaddflag         boolean NOT NULL,
    assesseeeditflag        boolean NOT NULL,
    assesseedeleteflag      boolean NOT NULL,
    viewpwdflag             boolean NOT NULL,
    backupflag              boolean NOT NULL,
    restoreflag             boolean NOT NULL,
    efilingflag             boolean NOT NULL,
    rptviewflag             boolean NOT NULL,
    editfiledreturnflag     boolean NOT NULL,
    selectedper             integer,
    createdby               integer NOT NULL,
    createdon               timestamp NOT NULL,
    modifiedby              integer NOT NULL,
    modifiedon              timestamp NOT NULL,
    isdeleted               boolean NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (prodkey, username)
);

-- ---------- FOREIGN KEYS (added last, order-independent) ----------
ALTER TABLE billhead     ADD CONSTRAINT fk_billhead_assessee
    FOREIGN KEY (subcode) REFERENCES assessee(subcode);
ALTER TABLE billdetails  ADD CONSTRAINT fk_billdetails_billhead
    FOREIGN KEY (billid) REFERENCES billhead(id) ON DELETE CASCADE;
ALTER TABLE billreceipts ADD CONSTRAINT fk_billreceipts_billhead
    FOREIGN KEY (billid) REFERENCES billhead(id);
