<#
.SYNOPSIS
  Issue (or update) a SmartTds licence — the API is the licence authority now.
  A user can only log in if a matching, active, non-expired licence exists and
  the firm is under its concurrent-seat cap.

.EXAMPLES
  .\create_licence.ps1 -ProdKey PYFA5V_1 -RegisteredTo "Acme & Co, CAs" -MaxSeats 5
  .\create_licence.ps1 -ProdKey DEMO12 -RegisteredTo "Trial User" -LicenceType Demo -ExpiryDate 2026-12-31
  # VPS: emit SQL only
  .\create_licence.ps1 -ProdKey PYFA5V_1 -RegisteredTo "Acme" -Container '' -OutFile lic.sql
#>
param(
    [Parameter(Mandatory=$true)][string]$ProdKey,
    [Parameter(Mandatory=$true)][string]$RegisteredTo,
    [ValidateSet('Full','Demo')][string]$LicenceType = 'Full',
    [string]$ExpiryDate,                       # yyyy-MM-dd; default = today + 1 year
    [int]$MaxSeats = 3,
    [string]$Container = "sttest",
    [string]$MasterDb  = "masterdbtds",
    [string]$OutFile
)
$ErrorActionPreference = "Stop"
if (-not $ExpiryDate) { $ExpiryDate = (Get-Date).AddYears(1).ToString('yyyy-MM-dd') }
$key = $ProdKey.Trim().ToUpperInvariant()
if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot "_licence_$key.sql" }
function Q([string]$s) { return $s.Replace("'", "''") }

$sql = @"
-- SmartTds licence upsert (generated by create_licence.ps1)
INSERT INTO licences (prodkey, registered_to, licence_type, expiry_date, max_seats, is_active, modified_on)
VALUES ('$(Q $key)','$(Q $RegisteredTo)','$LicenceType','$ExpiryDate',$MaxSeats,true, now())
ON CONFLICT (prodkey) DO UPDATE SET
  registered_to = EXCLUDED.registered_to, licence_type = EXCLUDED.licence_type,
  expiry_date = EXCLUDED.expiry_date, max_seats = EXCLUDED.max_seats,
  is_active = true, modified_on = now();
"@
[System.IO.File]::WriteAllText($OutFile, $sql, (New-Object System.Text.UTF8Encoding $false))
Write-Host "SQL written to $OutFile" -ForegroundColor Green

if ([string]::IsNullOrWhiteSpace($Container)) {
    Write-Host "No -Container. Run on target:  psql -d $MasterDb -f `"$OutFile`"" -ForegroundColor Yellow
    return
}
docker cp $OutFile "${Container}:/tmp/_create_licence.sql" | Out-Null
$o = docker exec $Container psql -U postgres -d $MasterDb -v ON_ERROR_STOP=1 -f /tmp/_create_licence.sql 2>&1
$err = $o | Select-String ERROR
if ($err) { Write-Host "ERROR:" -ForegroundColor Red; $err; exit 1 }
Write-Host "Licence '$key' -> '$RegisteredTo' ($LicenceType, $MaxSeats seats, expires $ExpiryDate)" -ForegroundColor Green
