<#
.SYNOPSIS
  Create (or update) a SmartTds login user with a correctly-hashed password.
  The hash format matches the API's PasswordHasher (PBKDF2-HMAC-SHA256:
  "pbkdf2$<iter>$<saltB64>$<hashB64>"), so the user can log in immediately.

.HOW IT WORKS
  Computes the hash, builds an idempotent INSERT ... ON CONFLICT UPSERT into
  masterdbtds.users, writes it to a .sql file, and (optionally) runs it.

.EXAMPLES
  # local Docker DB (default container 'sttest'):
  .\create_user.ps1 -Username admin -Password 'Test@123'

  # a normal (non-admin) user:
  .\create_user.ps1 -Username clerk1 -Password 'S3cret!' -UserType USER -Admin:$false

  # VPS / remote: just generate the SQL, then run it there with psql
  .\create_user.ps1 -Username admin -Password 'Strong#1' -Container '' -OutFile .\new_user.sql
  #   then on the server:  psql -d masterdbtds -f new_user.sql
#>
param(
    [Parameter(Mandatory=$true)][string]$Username,
    [Parameter(Mandatory=$true)][string]$Password,
    [string]$Name,
    [string]$ProdKey  = "DEMO123456",
    [string]$Email,
    [string]$Mobile   = "0000000000",
    [string]$UserType = "ADMIN",
    [bool]  $Admin    = $true,           # $true => all permission flags on
    [string]$Container = "sttest",       # set to '' to only generate the .sql (no execution)
    [string]$MasterDb  = "masterdbtds",
    [string]$OutFile
)
$ErrorActionPreference = "Stop"
if (-not $Name)    { $Name = $Username }
if (-not $Email)   { $Email = "$Username@local" }
if (-not $OutFile) { $OutFile = Join-Path $PSScriptRoot "_user_$Username.sql" }

# --- PBKDF2-HMAC-SHA256 (must match SmartTdsApi/Auth/PasswordHasher.cs) ---
$iter = 100000
$salt = New-Object byte[] 16
([System.Security.Cryptography.RandomNumberGenerator]::Create()).GetBytes($salt)
$alg  = [System.Security.Cryptography.HashAlgorithmName]::SHA256
$kdf  = New-Object System.Security.Cryptography.Rfc2898DeriveBytes($Password, $salt, $iter, $alg)
$hash = $kdf.GetBytes(32)
$pwdHash = "pbkdf2" + '$' + $iter + '$' + [Convert]::ToBase64String($salt) + '$' + [Convert]::ToBase64String($hash)

# escape single quotes for SQL string literals
function Q([string]$s) { return $s.Replace("'", "''") }
$flag = if ($Admin) { "true" } else { "false" }

$sql = @"
-- SmartTds user upsert (generated by create_user.ps1)
INSERT INTO users (prodkey, username, name, pwd, emailid, mobile, usertype,
  assesseeaddflag, assesseeeditflag, assesseedeleteflag, viewpwdflag, backupflag,
  restoreflag, efilingflag, rptviewflag, editfiledreturnflag,
  createdby, createdon, modifiedby, modifiedon, isdeleted)
VALUES ('$(Q $ProdKey)','$(Q $Username)','$(Q $Name)','$pwdHash','$(Q $Email)','$(Q $Mobile)','$(Q $UserType)',
  $flag,$flag,$flag,$flag,$flag,$flag,$flag,$flag,$flag, 1, now(), 1, now(), false)
ON CONFLICT (prodkey, username) DO UPDATE SET
  pwd = EXCLUDED.pwd, name = EXCLUDED.name, emailid = EXCLUDED.emailid,
  mobile = EXCLUDED.mobile, usertype = EXCLUDED.usertype, isdeleted = false,
  modifiedon = now();
"@

[System.IO.File]::WriteAllText($OutFile, $sql, (New-Object System.Text.UTF8Encoding $false))
Write-Host "SQL written to $OutFile" -ForegroundColor Green

if ([string]::IsNullOrWhiteSpace($Container)) {
    Write-Host "No -Container given. Run it on the target with:" -ForegroundColor Yellow
    Write-Host "  psql -d $MasterDb -f `"$OutFile`""
    return
}

docker cp $OutFile "${Container}:/tmp/_create_user.sql" | Out-Null
$o = docker exec $Container psql -U postgres -d $MasterDb -v ON_ERROR_STOP=1 -f /tmp/_create_user.sql 2>&1
$err = $o | Select-String ERROR
if ($err) { Write-Host "ERROR:" -ForegroundColor Red; $err; exit 1 }
Write-Host "User '$Username' created/updated in $MasterDb (login: $Username / <password>)  type=$UserType admin=$Admin" -ForegroundColor Green
